formspree_form_id: formspree_form_id
name: MIHOYOVERSE
title: MIHOYOVERSE | Download Honkai 3rd & Genshin Impact music!
description: Download Honkai 3rd and Genshin Impact game music, ost, bgm, and other audio!
tags:
  - honkai
  - genshin
  - music
  - bgm
  - ost
  - honkaiimpact
  - honkaiimpact3
  - honkaiimpact3rd
  - honkai3rd
  - genshinimpact
  - genshin_impact
  - game
  - mobile
  - arpg
  - openworld
  - anime
  - blog
show_hero: false
paginate: 12
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Feed
    url: /feed.xml
email: ""
disqus_username: ""
